# Generated by Django 5.0.3 on 2024-05-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SupportBot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botusers",
            name="language_code",
            field=models.CharField(
                choices=[("uz", "O'zbek"), ("ru", "Русский"), ("en", "English")],
                default="uz",
                max_length=10,
            ),
        ),
    ]
