# Generated by Django 5.0.3 on 2024-05-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SupportBot", "0002_alter_botusers_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botusers",
            name="phone",
            field=models.BigIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="botusers",
            name="telegram_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
