# Generated by Django 5.0.3 on 2024-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SupportBot", "0003_alter_botusers_phone_alter_botusers_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramchannelid",
            name="channel_id",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="telegramgroupid",
            name="group_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
