# Generated by Django 5.0.3 on 2024-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SupportBot", "0004_alter_telegramchannelid_channel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botusers",
            name="phone",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
