# Generated by Django 5.0.3 on 2024-05-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField()),
                ("facebook", models.URLField()),
                ("instagram", models.URLField()),
                ("twitter", models.URLField()),
                ("telegram", models.URLField()),
                ("youtube", models.URLField()),
                ("youtube_video", models.URLField()),
                ("image", models.ImageField(upload_to="home/")),
                ("logo", models.ImageField(upload_to="home/")),
            ],
            options={
                "verbose_name": "Home",
                "verbose_name_plural": "Home",
                "db_table": "home",
            },
        ),
    ]
