# Generated by Django 5.0.3 on 2024-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("useremail", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "verbose_name_plural": "Sayt Foydalanuvchilar",
                "db_table": "site_user",
            },
        ),
    ]
